# 配置文件版本(请勿修改)
version: 8
# 是否自动下载插件更新
update: false
# 插件提示信息显示前缀
prefix: '&bZMusic &e>>> &r'

# 是否开启调试模式
debug: false

# API设置
api:
  # 网易云音乐API地址
  #
  # 使用开源项目NeteaseCloudMusicApi
  # 推荐自行部署，需Node.js环境
  # 地址: https://github.com/Binaryify/NeteaseCloudMusicApi
  netease: 'https://netease.api.zhenxin.xyz/'
  # QQ音乐API地址
  #
  # 使用开源项目QQMusicApi
  # 推荐自行部署，需Node.js环境
  # 地址: https://github.com/jsososo/QQMusicApi
  qq: 'https://qqmusic.api.zhenxin.xyz/'

# 账号设置
account:
  # 网易云音乐
  netease:
    # 登录方式
    #
    # email - 邮箱登录(密码处填写邮箱密码)
    # phone - 手机号登录(密码处填写网易云密码)
    loginType: phone
    # 账号
    #
    # 邮箱登录填写邮箱
    # 手机号登录填写手机号
    account: 18888888888
    # 密码
    #
    # 邮箱登录填写邮箱密码
    # 手机号登录填写网易云密码
    password: a123456
    # 密码方式
    #
    # normal = 纯密码 由插件通过md5加密上传到服务器验证
    # md5 = 纯md5 由用户通过md5加密设置在配置文件 插件读取上传到服务器验证
    passwordType: normal
    # 是否关注作者的网易云音乐账号
    follow: true
  # 哔哩哔哩
  bilibili:
    # 由于哔哩哔哩为m4a音频格式
    # 需要服务器用来转换
    # 因此哔哩哔哩播放功能收费5元/永久
    # 联系作者获取授权
    #
    # 授权QQ
    qq: 1307993674
    # 授权Key
    key: none

# 点歌设置
music:
  # 点歌扣除的金币(设置为0则不扣除)
  # 拥有zmusic.bypass的玩家无视扣除
  money: 10
  # 点歌的冷却时间(设置为0则无冷却)
  # 拥有zmusic.bypass的玩家无视冷却
  cooldown: 5

# 歌词设置
lyric:
  # 是否启用歌词
  enable: true
  # 是否显示歌词翻译
  showLyricTr: true
  # 歌词颜色
  color: '&b'
  # 以下为显示方式设置，可同时启用
  # 是否使用BossBar显示歌词(不支持1.8及以下)
  bossBar: true
  # 是否使用ActionBar显示歌词
  actionBar: false
  # 是否使用Title显示歌词
  subTitle: false
  # 是否使用聊天信息显示歌词
  chatMessage: false
  # Hud 设置(仅支持1.12及以上)
  hud:
    # 是否启用Hud
    enable: true
    # 信息的X坐标
    infoX: 2
    # 信息的Y坐标
    infoY: 12
    # 歌词的X坐标
    lyricX: 2
    # 歌词的Y坐标
    lyricY: 52