[versions]
kotlin = "2.0.0-Beta4"
blossom = "2.1.0"
shadow = "8.1.1"
spigot = "1.19.4-R0.1-SNAPSHOT"
bungeecord = "1.19-R0.1-SNAPSHOT"
velocity = "3.1.1"
hutool = "6.0.0-M11"
netty = "4.1.97.Final"
placeholderapi = "2.11.5"
nightconfig = "3.6.7"
bstats = "3.0.2"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kyori-blossom = { id = "net.kyori.blossom", version.ref = "blossom" }
johnrengelman-shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadow" }

[libraries]
# Platform API
spigot = { module = "org.spigotmc:spigot-api", version.ref = "spigot" }
bungeecord = { module = "net.md-5:bungeecord-api", version.ref = "bungeecord" }
velocity = { module = "com.velocitypowered:velocity-api", version.ref = "velocity" }
# hutool
hutool-core = { module = "org.dromara.hutool:hutool-core", version.ref = "hutool" }
hutool-http = { module = "org.dromara.hutool:hutool-http", version.ref = "hutool" }
hutool-json = { module = "org.dromara.hutool:hutool-json", version.ref = "hutool" }
# netty
netty-buffer = { module = "io.netty:netty-buffer", version.ref = "netty" }
# PAPI
placeholderapi = { module = "me.clip:placeholderapi", version.ref = "placeholderapi" }
# Night Config
nightconfig-core = { module = "com.electronwill.night-config:core", version.ref = "nightconfig" }
nightconfig-toml = { module = "com.electronwill.night-config:toml", version.ref = "nightconfig" }
# bStats
bstats-bukkit = { module = "org.bstats:bstats-bukkit", version.ref = "bstats" }
bstats-bungeecord = { module = "org.bstats:bstats-bungeecord", version.ref = "bstats" }
bstats-velocity = { module = "org.bstats:bstats-velocity", version.ref = "bstats" }

[bundles]
hutool = ["hutool-core", "hutool-http", "hutool-json"]
nightconfig = ["nightconfig-core", "nightconfig-toml"]